server:
  port: 9000

spring:
  application:
    name: USER-AUTHENTICATION-SERVER
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/test_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true