apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-authentication-server-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-authentication-server-app
  template:
    metadata:
      labels:
        app: user-authentication-server-app
    spec:
      containers:
        - name: user-authentication-server-app
          image: ecr/user-authentication-server:latest  # plz choose the ecr path
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          resources:
            requests:
              cpu: 0.5
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db_password
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: db_username
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: db_url