# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Main build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.img/**'
      - '.setup/docker/**'
      - '.setup/utils/**'
      - '.setup/**.sh'
  workflow_dispatch:

env:
  K8S_CLUSTER_ID: "k8s-cluster"
  K8S_YAML_PATH: ./.deploy
  JAVA_VERSION: '11'
  JAVA_DISTRIBUTION: 'temurin'
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK}}
  M2_SETTINGS_XML_ACTIVE_PROFILES: '["github"]'
  M2_SETTINGS_XML_REPOSITORIES: >
    [
      {
        "id": "central",
        "url": "https://repo1.maven.org/maven2"
      },
      {
        "id": "yky32",
        "url": "https://maven.pkg.github.com/yky32/spring-boot-starter-app-core",
        "snapshots": {
          "enabled": "true"
        }
      }
    ]
  M2_SETTINGS_XML_SERVER: >
    [
      { "id": "github", "username": "yky32", "password": "${{ secrets.MAVEN_GITHUB_TOKEN }}" },
      { "id": "docker.io", "username": "${{ secrets.DOCKER_USERNAME }}", "password": "${{ secrets.DOCKER_PASSWORD }}" } 
    ]

jobs:

  start:
    if: ${{ !contains(github.event.head_commit.message, '[no]')}}
    runs-on: ubuntu-latest
    steps:
      - name: List of the github context environment variables
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List of the GitHub Actions environment variables on ubuntu-latest
        run: env

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Set up ~.m2/settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          active_profiles: ${{ env.M2_SETTINGS_XML_ACTIVE_PROFILES }}
          repositories: ${{ env.M2_SETTINGS_XML_REPOSITORIES }}
          servers: ${{ env.M2_SETTINGS_XML_SERVER }}

      - name: Run Maven Test
        run: mvn test --file pom.xml

  test-finish:
    if: ${{ failure() }}
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Curl for Fail Test Alert
        run: |
          curl --request POST \
          --header 'content-type: application/json' \
          --url ${{ env.DISCORD_WEBHOOK }} \
          --data '{
            "username": "Sorry-fail-test-${{ github.event.repository.name }}@__${{ github.run_number }}",
            "content":  "${{ github.event.head_commit.message }} ___ @by ${{ github.event.sender.login }} - ${{ github.event.head_commit.timestamp }} "
          }'

  build-service-image:
    needs: [  test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List of the GitHub Actions environment variables on ubuntu-latest
        run: env

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Set up ~.m2/settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          active_profiles: ${{ env.M2_SETTINGS_XML_ACTIVE_PROFILES }}
          repositories: ${{ env.M2_SETTINGS_XML_REPOSITORIES }}
          servers: ${{ env.M2_SETTINGS_XML_SERVER }}

      - name: Building and Pushing [profile-service]
        run: mvn package -Dmaven.test.skip dockerfile:push --file ./pom.xml